### ISSUE TITLE
Cmd show up then close directly

### ISSUE THREAD

**Issue by CelhrynOfficial** [AntiSSTools/HackMelter#2]
I downloaded all version and no one works with me. I open up Uni.bat and cmd show up then close directly. Running as admin doesnt change anything and even with antivirus disabled it doesnt work... please help

**Comment by craciu25yt** [comment]
it is a RAT

**Comment by AntiSSTools** [comment]
Hey! It is not a RAT, in fact, we have already shut down. If you see my commits, last commit was long ago.
Our servers got suspended due to invoice not paid, so if you open you will see that CMD pop up and close (meaning that server is offline).
Thanks.
PS: If you want to contribute so I can buy a new VPS let me know, donations are accepted :)
