### ISSUE TITLE
do not open

### ISSUE THREAD

**Issue by craciu25yt** [AntiSSTools/HackMelter#3]
just a weird malware that is heavily obfuscated, (maybe) using antivirus evasion techinques 
![image](https://github.com/AntiSSTools/HackMelter/assets/48807342/eeb5bfd1-ea3f-4edb-9dc1-ed4cff9bf96f)
runs vba 
![image](https://github.com/AntiSSTools/HackMelter/assets/48807342/1f5597f6-69b0-4f6b-a70a-07947ce2e67e)
and makes a bsod. Idk what happens after that because triage after getting bsoded doesn't turn on again

![image](https://github.com/AntiSSTools/HackMelter/assets/48807342/6df332d9-4cd1-4290-8306-96a600fab361)

**Comment by AntiSSTools** [comment]
Of course, HackMelter is completely obfuscated, _why wouldnt it?_
Someone can get the source code and steal the project. That is why its obfuscated on a 9-layer cipher. It is practically unreverseable because you need credentials for the server (it's off at the moment), that is why when you open it it closes, the server is **OFFLINE**.
So, stop making fake acussations of malware, when the server is literally off. I can even show you a screenshot of invoice unpaid.

**Comment by AntiSSTools** [comment]
The file will not run until the server is back up, which can lead to a recode of the whole project due to the machine.
The program uses a bit of antivirus evasion because many people asked for it, many people were getting false-flagged by windows defender, so I encoded a bit everything _(also due to the fact that Echo and Paladin needed a ciphering for this)_.

**Comment by craciu25yt** [comment]
bro it literally makes  bsod

**Comment by craciu25yt** [comment]
tho unless you are really good to this (don't think so, u would use c++ or smh) it shouldn't be that hard. It is a batch script that runs some ps & vba. But too many gibberish
